### ISSUE TITLE
OpenBSD CI template

### ISSUE THREAD

**Issue by adamsteen** [Solo5/solo5-ci#2]
I am working towards building an OpenBSD CI template, will update here as I progress.

**Comment by mato** [comment]
The CI setup is under-documented right now, but what I need from the template are the steps, or a script to run, on a freshly installed OpenBSD VM to get a running `surf-build` and the build dependencies for Solo5. If you need more information, please ask.

**Comment by adamsteen** [comment]
notes to get "solo5-vm-build.sh" runnings on OpenBSD (fresh install of current)

`pkg_add bash coreutils git gmake node`

```
mkdir ~/.node
echo 'prefix = $HOME/.node' > $HOME/.npmrc
echo 'export PATH="$HOME/.node/bin:$PATH"\nexport NODE_PATH="$HOME/.node/lib/node_modules:$NODE_PATH"' >> $HOME/.profile
git clone --depth=1 https://github.com/surf-build/surf
cd surf && git checkout v2.0.0-beta.4 && npm install --no-optional && npm pack
npm install -g --unsafe-perm --no-optional surf-build-2.0.0-beta.4.tgz
git clone https://github.com/Solo5/solo5-ci.git
GITHUB_USER=.. GITHUB_TOKEN=... surf-run -r https://github.com/<username>/<repo> -- $HOME/solo5-ci/scripts/solo5-vm-build.sh
```

**Comment by adamsteen** [comment]
i thought i had a working script for OpenBSD -> https://github.com/adamsteen/solo5-ci/tree/master/amd64-OpenBSD64-clang60

but upon testing `surf-run`  
`surf-run -r https://github.com/adamsteen/solo5 -- surf-build -n amd64-OpenBSD64-clang60`

```
Building https://github.com/adamsteen/solo5@0f3c6e3c67f5e314a85f1b0d6e9fe9e92e0ec84d (refs/heads/master)                                │
Build Errored: Git not supported on platform: openbsd                                                                                   │
                                                                                                                                        │
Fatal Error: Git not supported on platform: openbsd                                                                                     │
                                                                                                                                        │
Error: Failed with exit code: 255                                                                                                       │
    at SafeSubscriber._next (/home/surf/.node/lib/node_modules/surf-build/node_modules/spawn-rx/lib/src/index.js:251:71)                │
    at SafeSubscriber.__tryOrSetError (/home/surf/.node/lib/node_modules/surf-build/node_modules/rxjs/Subscriber.js:251:16)             │
    at SafeSubscriber.next (/home/surf/.node/lib/node_modules/surf-build/node_modules/rxjs/Subscriber.js:191:27)                        │
    at Subscriber._next (/home/surf/.node/lib/node_modules/surf-build/node_modules/rxjs/Subscriber.js:129:26)                           │
    at Subscriber.next (/home/surf/.node/lib/node_modules/surf-build/node_modules/rxjs/Subscriber.js:93:18)                             │
    at DefaultIfEmptySubscriber._next (/home/surf/.node/lib/node_modules/surf-build/node_modules/rxjs/operators/defaultIfEmpty.js:67:26)│
    at DefaultIfEmptySubscriber.Subscriber.next (/home/surf/.node/lib/node_modules/surf-build/node_modules/rxjs/Subscriber.js:93:18)    │
    at TakeLastSubscriber._complete (/home/surf/.node/lib/node_modules/surf-build/node_modules/rxjs/operators/takeLast.js:102:29)       │
    at TakeLastSubscriber.Subscriber.complete (/home/surf/.node/lib/node_modules/surf-build/node_modules/rxjs/Subscriber.js:118:18)     │
    at ScanSubscriber.Subscriber._complete (/home/surf/.node/lib/node_modules/surf-build/node_modules/rxjs/Subscriber.js:136:26)        │
    at ScanSubscriber.Subscriber.complete (/home/surf/.node/lib/node_modules/surf-build/node_modules/rxjs/Subscriber.js:118:18)         │
    at MergeMapSubscriber._complete (/home/surf/.node/lib/node_modules/surf-build/node_modules/rxjs/operators/mergeMap.js:137:30)       │
    at MergeMapSubscriber.Subscriber.complete (/home/surf/.node/lib/node_modules/surf-build/node_modules/rxjs/Subscriber.js:118:18)     │
    at ArrayObservable._subscribe (/home/surf/.node/lib/node_modules/surf-build/node_modules/rxjs/observable/ArrayObservable.js:116:24) │
    at ArrayObservable.Observable._trySubscribe (/home/surf/.node/lib/node_modules/surf-build/node_modules/rxjs/Observable.js:172:25)   │
    at ArrayObservable.Observable.subscribe (/home/surf/.node/lib/node_modules/surf-build/node_modules/rxjs/Observable.js:160:93)       │
    at MergeMapOperator.call (/home/surf/.node/lib/node_modules/surf-build/node_modules/rxjs/operators/mergeMap.js:87:23)               │
    at Observable.subscribe (/home/surf/.node/lib/node_modules/surf-build/node_modules/rxjs/Observable.js:157:22)                       │
    at ScanOperator.call (/home/surf/.node/lib/node_modules/surf-build/node_modules/rxjs/operators/scan.js:69:23)                       │
    at Observable.subscribe (/home/surf/.node/lib/node_modules/surf-build/node_modules/rxjs/Observable.js:157:22)                       │
    at TakeLastOperator.call (/home/surf/.node/lib/node_modules/surf-build/node_modules/rxjs/operators/takeLast.js:65:23)               │
    at Observable.subscribe (/home/surf/.node/lib/node_modules/surf-build/node_modules/rxjs/Observable.js:157:22)                       │
Failed with exit code: 255 
```

will look into this futher

**Comment by adamsteen** [comment]
this change needs a Pull Request [dugite #200](https://github.com/desktop/dugite/pull/200) to be applied

then i will open a Pull Request for [adamsteen/solo5-ci](https://github.com/adamsteen/solo5-ci)

**Comment by adamsteen** [comment]
We should be able to close this with PR #3

**Comment by mato** [comment]
Done in ff50dcd, much easier now with 6.4 and surf 2.0.0. Thanks for the investigation.
